version: "v3.0"
name: My first pipeline
semaphore_image: standard
blocks:
  - name: "Stage 1 1️⃣"
    build:
      prologue:
        commands:
      jobs:
      - name: First job ㍊xy
        commands:
          - checkout && cd $SEMAPHORE_GIT_DIR
          - pwd
          - echo "test"
          - ls /sdsd

      - name: Looooping 🔁
        env_vars:
          - name: VAR1
            value: Environment Variable 1
          - name: PI
            value: "3.14159"
        commands:
          - echo "First env var: $VAR1"
          - echo "My files:"
          - ls -lah
      epilogue:
        commands:
          - echo "Yay job finished"
          - echo $SEMAPHORE_JOB_RESULT

  - name: "Stage 2 🧝‍♀️"
    build:
      jobs:
        - name: Job from 1st block
          commands:
            - checkout
            - cd $SEMAPHORE_GIT_DIR
            - echo $SEMAPHORE_PIPELINE_ID
            - echo "Firsdt job 1"
            - echo "First job 2"
            - echo "First job 3"
            - pwd

