version: "v3.0"
name: My first pipeline
semaphore_image: standard
blocks:
  - name: "Stage 1 1️⃣"
    build:
      jobs:
      - name: First job ㍊xy
        commands:
          - checkout && cd $SEMAPHORE_GIT_DIR
          - pwd
          - echo "test"

      - name: Looooping 🔁
        commands:
          - checkout
          - cd elixir-cookbook
          - echo "My files:"
          - ls -lah

  - name: "Stage 2 🧝‍♀️"
    build:
      jobs:
        - name: Job from 1st block
          commands:
            - checkout
            - cd $SEMAPHORE_GIT_DIR
            - echo $SEMAPHORE_PIPELINE_ID
            - echo "Firsdt job 1"
            - echo "First job 2"
            - echo "First job 3"
            - pwd

